# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - deploy # Or 'main', depending on your primary branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    # ADD THIS PERMISSIONS BLOCK HERE:
    permissions:
      contents: write # This grants write permission to the GITHUB_TOKEN for this job

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build project and prepare 404.html
        run: |
          npm run build
          cp dist/index.html dist/404.html
        env:
          VITE_APP_GITHUB_TOKEN: ${{ secrets.VITE_APP_GITHUB_TOKEN }}
          VITE_CLERK_PUBLISHABLE_KEY: ${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }} # <--- ADD THIS LINE

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Ensure this is GITHUB_TOKEN
          publish_dir: ./dist
          publish_branch: gh-pages
          # cname: opensource.techquanta.tech